### PR TITLE
Create the first EDA notebook

### PR DESCRIPTION
**Pull request by alcazar90**
Closes issue #50.

- Create the `eda` directory and the first EDA notebook.
- Add checkpoints files into .gitignore

It's left to write how to run the notebooks in the README. 

best,

### CODE REVIEW

**Comment by shreyashankar** [comment]
Thanks for this! Will review today or tomorrow :)

**Comment by alcazar90** [comment]
Hi @shreyashankar ,

I used the following commands to work on the notebook.

```bash
# initialize the container; note that we bind the notebooks' directory 
# between the container and your local system to save the notebook's progress.
docker run -d -p 8888:8888 --env-file=./.env --mount type=bind,src="$PWD"/eda,dst=/app/eda toy-ml-pipeline

# navigate inside the container filesystem
docker exec -t -i toy-ml-pipeline /bin/bash

# move to app directory where the project files lives
cd app

# start the jupyter notebook server
jupyter notebook --ip 0.0.0.0 --allow-root
```

Maybe we can add in some part of the README the jupyer-docker workflow. As a beginner, figuring out how to work on jupyter notebooks within a container is a bit tricky.


By the way, happy new year 🎉!

**Review by shreyashankar — APPROVED** [review]
This is excellent! Users don't need to run notebooks via Docker, but it's great that you have the instructions in the PR. Thank you for the detailed notebook :)

**Comment by shreyashankar** [comment]
Closes #50

**Pull request merged**
